adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoriesListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.MyLogoutView.as_view(), name='logout'),
    path('register/', authapp.UserRegisterView.as_view(), name='register'),
    path('edit/', authapp.UserUpdateView.as_view(), name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify')
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import main, contact


app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contact/', contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not field_name.startswith('is_'):
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not field_name.startswith('is_'):
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, render

from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm

from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView, DeleteView, CreateView


class DispatchMixin:
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class UsersListView(DispatchMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'objects'
    paginate_by = 2
    extra_context = {'title': 'админка/пользователи'}

    # def get_context_data(self, **kwargs):
    #     context = super(UsersListView, self).get_context_data(**kwargs)
    #     context['title'] = 'админка/пользователи'
    #     return context


class UserCreateView(DispatchMixin, CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')
    fields = '__all__'
    extra_context = {'title': 'пользователи/создание'}


class UserUpdateView(DispatchMixin, UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')
    fields = '__all__'
    extra_context = {'title': 'пользователи/редактирование'}

    def get_form(self, form_class=None):
        form = super().get_form()
        for field_name, field in form.fields.items():
            if not field_name.startswith('is_'):
                field.widget.attrs['class'] = 'form-control'
        return form


class UserDeleteView(DeleteView):
    model = ShopUser
    success_url = reverse_lazy('admin_staff:users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class CategoriesListView(DispatchMixin, ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    context_object_name = 'objects'
    paginate_by = 2
    extra_context = {'title': 'админка/категории'}


class CategoryCreateView(DispatchMixin, CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    fields = '__all__'
    extra_context = {'title': 'категории/создание'}


class CategoryUpdateView(DispatchMixin, UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    fields = '__all__'
    extra_context = {'title': 'категории/редактирование'}

    def get_form(self, form_class=None):
        form = super().get_form()
        for field_name, field in form.fields.items():
            if not field_name.startswith('is_'):
                field.widget.attrs['class'] = 'form-control'
        return form


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('admin_staff:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ProductsListView(DispatchMixin, ListView):
    model = Product
    template_name = 'adminapp/products.html'
    context_object_name = 'objects'
    ordering = ('-is_active', 'name')
    paginate_by = 3
    extra_context = {'title': 'админка/продукт'}

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        queryset = [p for p in queryset if p.category_id == self.kwargs['pk']]
        return queryset


class ProductCreateView(DispatchMixin, CreateView):
    model = Product
    template_name = 'adminapp/user_update.html'
    # success_url = reverse_lazy('admin_staff:users')
    fields = '__all__'
    extra_context = {'title': 'продукт/создание'}

    def get_success_url(self):
        return reverse_lazy('admin_staff:products', kwargs={'pk': self.object.category_id})

    def get_form(self, form_class=None):
        category = get_object_or_404(ProductCategory, pk=self.kwargs['pk'])
        form = super().get_form()
        for field_name, field in form.fields.items():
            if field_name == 'category':
                field.initial = category
            if not field_name.startswith('is_'):
                field.widget.attrs['class'] = 'form-control'
        return form


class ProductUpdateView(DispatchMixin, UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    fields = '__all__'
    extra_context = {'title': 'продукт/редактирование'}

    def get_success_url(self):
        return reverse_lazy('admin_staff:products', kwargs={'pk': self.object.category_id})

    def get_form(self, form_class=None):
        form = super().get_form()
        for field_name, field in form.fields.items():
            if not field_name.startswith('is_'):
                field.widget.attrs['class'] = 'form-control'
        return form


class ProductDeleteView(DeleteView):
    model = Product

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('admin_staff:products', kwargs={'pk': self.object.category_id})

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
{% load my_tags %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/style.css' %}">
    <link rel="stylesheet" href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">

    {% block css %}
    {% endblock %}

    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js' ></script>
    <script src="{% static 'adminapp/script.js' %}"></script>

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
    <header class="header" id="header">
        <div class="header_toggle">
            <i class='bx bx-menu' id="header-toggle"></i>
        </div>
        <div class="header_img">
            <img src="{{ user.avatar|media_folder_users }}" alt="">
        </div>
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div>
                <a href="{% url 'index' %}" class="nav_logo">
                    <i class='bx bx-layer nav_logo-icon'></i>
                    <span class="nav_logo-name">Админка</span>
                </a>
                <div class="nav_list">
                    {% include 'adminapp/inc/inc_menu.html' %}
                </div>
            </div>
            <a href="{% url 'auth:logout' %}" class="nav_link">
                <i class='bx bx-log-out nav_icon'></i>
                <span class="nav_name">Выход</span>
            </a>
        </nav>
    </div>
    <div class="height-100 bg-light">
        <h4>{{ title }}</h4>
        <div class="mb-3">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="card">
        <ul class="list-group list-group-flush">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">Описание</th>
                        <th scope="col">удаление</th>
                        <th scope="col">редактирование</th>
                        <th scope="col">удаление</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">Описание</th>
                        <th scope="col">удаление</th>
                        <th scope="col">редактирование</th>
                        <th scope="col">удаление</th>
                    </tr>
                </tfoot>
                <tbody>
                    {% for object in objects %}
                        <tr>
                            <td>
                                <a href="{% url 'admin_staff:products' object.id %}" style="color: dodgerblue">
                                    {{ object.name }}
                                </a>
                            </td>
                            <td>{{ object.description }}</td>
                            <td>
                                {% if object.is_active %}
                                    <i class="fa fa-check-circle"></i>
                                {% else %}
                                    <i class="fa fa-times-circle"></i>
                                {% endif %}
                            </td>
                            <td>
                                <a type="button" href="{% url 'admin_staff:category_update' object.id %}"
                                        class="btn btn-info" style="width: 140px">
                                    Редактировать
                                </a>
                            </td>
                            <td>
                                {% if object.is_active %}
                                    <form action="{% url 'admin_staff:category_delete' pk=object.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="submit" class="btn btn-danger" style="width: 130px" value="Удалить"></p>
                                    </form>
                                {% else %}
                                    <form action="{% url 'admin_staff:category_delete' pk=object.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="submit" class="btn btn-primary" style="width: 130px" value="Восстановить"></p>
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <li class="list-group-item">
                <a href="{% url 'admin_staff:category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </li>
            <li class="list-group-item">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">
                        <
                    </a>
                {% endif %}
                <span class="current">
                    страница {{ page_obj.number }} из {{ paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">
                      >
                    </a>
                {% endif %}
            </li>
        </ul>
    </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
{% endblock %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="сохранить">
    </form>
    <a href="{% url 'admin_staff:categories' %}">
        <button type="button" class="btn btn-success">
            К списку категорий
        </button>
    </a>

{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
{% endblock %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="сохранить">
    </form>
    <a href="{{ request.META.HTTP_REFERER }}">
        <button type="button" class="btn btn-success">
            Назад
        </button>
    </a>

{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="card">
        <ul class="list-group list-group-flush">
            <table class="table">
        <thead>
            <tr>
                <th scope="col">Картинка</th>
                <th scope="col">Название</th>
                <th scope="col">Описание</th>
                <th scope="col">Количество</th>
                <th scope="col">Цена</th>
                <th scope="col">Удалить</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th scope="col">Картинка</th>
                <th scope="col">Название</th>
                <th scope="col">Описание</th>
                <th scope="col">Количество</th>
                <th scope="col">Цена</th>
                <th scope="col">Удалить</th>
            </tr>
        </tfoot>
        <tbody>
            {% for object in objects %}
                <tr>
                    <td>
                        <img src="{{ object.image|media_folder_products }}" style="width: 100px">
                    </td>
                    <td>
                        <a href="{% url 'admin_staff:product_update' object.id %}" style="color: dodgerblue">
                            {{ object.name }}
                        </a>
                    </td>
                    <td>{{ object.short_desc }}</td>
                    <td>{{ object.quantity }}</td>
                    <td>{{ object.price }}</td>
                    <td>
                        {% if object.is_active %}
                            <form action="{% url 'admin_staff:product_delete' pk=object.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-danger" style="width: 130px" value="Удалить">
                            </form>
                        {% else %}
                            <form action="{% url 'admin_staff:product_delete' pk=object.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-primary" style="width: 130px" value="Восстановить"><
                            </form>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
            <li class="list-group-item">
                <a href="{% url 'admin_staff:product_create' request.resolver_match.kwargs.pk %}">
                    <button class="btn btn-success">Создать продукт</button>
                </a>
            </li>
        <li class="list-group-item">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">
                        <
                    </a>
                {% endif %}
                <span class="current">
                    страница {{ page_obj.number }} из {{ paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">
                      >
                    </a>
                {% endif %}
            </li>
        </ul>
    </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
{% endblock %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="сохранить">
    </form>
    <a href="{% url 'admin_staff:users' %}">
        <button type="button" class="btn btn-success">
            К списку пользователей
        </button>
    </a>

{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="card">
        <ul class="list-group list-group-flush">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">автар</th>
                        <th scope="col">login</th>
                        <th scope="col">Имя</th>
                        <th scope="col">Фамилия</th>
                        <th scope="col">email</th>
                        <th scope="col">Персонал сайта</th>
                        <th scope="col">Активный</th>
                        <th scope="col">Удалить</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th scope="col">автар</th>
                        <th scope="col">login</th>
                        <th scope="col">Имя</th>
                        <th scope="col">Фамилия</th>
                        <th scope="col">email</th>
                        <th scope="col">Персонал сайта</th>
                        <th scope="col">Активный</th>
                        <th scope="col">Удалить</th>
                    </tr>
                </tfoot>
                <tbody>
                {% for object in objects %}
                    <tr>
                        <th scope="col">
                            <img src='{{ object.avatar|media_folder_users }}' style="height: 50px;">
                        </th>
                        <td>
                            <a href="{% url 'admin_staff:user_update' object.id %}" style="color: dodgerblue">
                                {{ object.username }}
                            </a>
                        </td>
                        <td>{{ object.first_name }}</td>
                        <td>{{ object.last_name }}</td>
                        <td>{{ object.email }}</td>
                        <td>
                            {% if object.is_staff %}
                                <i class="fa fa-check-circle"></i>
                            {% else %}
                                <i class="fa fa-times-circle"></i>
                            {% endif %}
                        </td>
                        <td>
                            {% if object.is_active %}
                                <i class="fa fa-check-circle"></i>
                            {% else %}
                                <i class="fa fa-times-circle"></i>
                            {% endif %}
                        </td>
                        <td>
                            {% if object.is_active %}
                                <form action="{% url 'admin_staff:user_delete' pk=object.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-danger" style="width: 130px" value="Удалить"></p>
                                </form>
                            {% else %}
                                <form action="{% url 'admin_staff:user_delete' pk=object.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-primary" style="width: 130px" value="Восстановить"></p>
                                </form>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>
            <li class="list-group-item">
                <a href="{% url 'admin_staff:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </li>
            <li class="list-group-item">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">
                        <
                    </a>
                {% endif %}
                <span class="current">
                    страница {{ page_obj.number }} из {{ paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">
                      >
                    </a>
                {% endif %}
            </li>
        </ul>
    </div>
{% endblock %}