basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.BasketView.as_view(), name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.BasketDeleteView.as_view(), name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

mainapp/urls.py
from django.urls import path
from .views import ProductsView, ProductView

app_name = 'mainapp'

urlpatterns = [
    path('', ProductsView.as_view(), name='products'),
    path('category/<int:pk>/', ProductsView.as_view(), name='category'),
    # path('category/<int:pk>/page/<int:page>', ProductsView.as_view(), name='page'),
    path('product/<int:pk>/', ProductView.as_view(), name='product'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import main, contact


app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contact/', contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='активный',
        db_index=True,
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, verbose_name='Категория', on_delete=models.CASCADE)
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )
    image = models.ImageField(
        upload_to='products_images',
        blank=True,
    )
    short_desc = models.CharField(
        verbose_name='краткое описание продукта',
        max_length=60,
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание продукта',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='активный',
        db_index=True,
    )

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
from django.core.cache import cache
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from django.conf import settings
from .models import ProductCategory, Product
from basketapp.models import Basket
import random


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_oredered_by_price():
    if settings.LOW_CACHE:
        key = 'products_oredered_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_oredered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_oredered_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


class ProductsView(ListView):
    model = Product
    ordering = 'price'
    context_object_name = 'products'
    paginate_by = 3

    def get_template_names(self):
        if 'pk' in self.kwargs:
            return ['mainapp/products_list.html']
        else:
            return ['mainapp/products.html']

    # def get_basket(self):
    #     if self.request.user.is_authenticated:
    #         return Basket.objects.filter(user=self.request.user)
    #     else:
    #         return []

    def get_hot_product(self):
        products = get_products()
        return random.sample(list(products), 1)[0]
#        return random.sample(list(self.get_queryset()), 1)[0]

    def get_same_products(self, ):
        hot_product = self.get_hot_product()
        same_products = self.get_queryset().filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
        return same_products

    def get_queryset(self):
        queryset = get_products_oredered_by_price()
        # queryset = super(ProductsView, self).get_queryset()
        if 'pk' in self.kwargs:
            if self.kwargs['pk'] == 0:
                return queryset
            else:
                # queryset = queryset.filter(category_id__pk=self.kwargs['pk'])
                # return queryset
                return get_products_in_category_oredered_by_price(self.kwargs['pk'])
        else:
            return queryset

    def get_category(self):
        if 'pk' in self.kwargs:
            if self.kwargs['pk'] == 0:
                category = {
                    'pk': 0,
                    'name': 'все'}
            else:
                category = get_category(self.kwargs['pk'])
#                category = get_object_or_404(ProductCategory, pk=self.kwargs['pk'])
            return category

    def get_context_data(self, **kwargs):
        context = super(ProductsView, self).get_context_data(**kwargs)
        # context['basket'] = self.get_basket()
        context['title'] = 'продукты'
        context['links_menu'] = get_links_menu()
        context['category'] = self.get_category()
        context['hot_product'] = self.get_hot_product()
        context['same_products'] = self.get_same_products()
        return context


class ProductView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'mainapp/product.html'

    # def get_basket(self):
    #     if self.request.user.is_authenticated:
    #         return Basket.objects.filter(user=self.request.user)
    #     else:
    #         return []
    def get_object(self, queryset=None):
        return get_product(self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        # context['basket'] = self.get_basket()
        context['title'] = 'продукт'
        context['links_menu'] = get_links_menu()

        return context

mainapp/templates/mainapp/product.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block menu %}
	<div class="hero-white">
			<div class="header clearfix">
				{% include 'inc/inc_menu.html' %}
			</div>
		</div>
{% endblock %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/inc/inc_categories_menu.html' %}
    </div>
    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="{{ product.image|media_folder_products }}"
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="{{ product.image|media_folder_products }}" alt="вариант 1" style="width: 70px;">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="{{ product.image|media_folder_products }}" alt="вариант 2" style="width: 70px;">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="{{ product.image|media_folder_products }}" alt="вариант 3" style="width: 70px;">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать 
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block menu %}
	<div class="hero-white">
			<div class="header clearfix">
				{% include 'inc/inc_menu.html' %}
			</div>
		</div>
{% endblock %}

{% block content %}
	<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/inc/inc_categories_menu.html' %}
			</div>
			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{{ hot_product.image|media_folder_products }}" width="100%">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{{ hot_product.image|media_folder_products }}" width="70px" alt=""></a>
						</div>
						<div class="block">
							<a href="#"><img src="{{ hot_product.image|media_folder_products }}" width="70px" alt=""></a>
						</div>
						<div class="block">
							<a href="#"><img src="{{ hot_product.image|media_folder_products }}"  width="70px" alt=""></a>
						</div>
					</div>
				</div>
				<div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price">{{ hot_product.price }} <span>руб</span></p>
					<a href="{% url 'products:product' hot_product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
					  {{ hot_product.short_desc }}
					</div>
				</div>
			</div>


			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="/static/img/product-11.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/static/img/product-21.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/static/img/product-31.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block menu %}
  <div class="hero-white">
    <div class="header clearfix">
        {% include 'inc/inc_menu.html' %}
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/inc/inc_categories_menu.html' %}
    </div>

    <div class="products_list">
      <div class="title clearfix">
        <h2>
          Категория: "{{ category.name|title }}"
        </h2>
        <div class="paginator">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">
                    <
                </a>
            {% endif %}
            <span class="current">
                страница {{ page_obj.number }} из {{ paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">
                  >
                </a>
            {% endif %}
        </div>
      </div>
      <div class="category-products clearfix">
        {% for product in products %}
          <div class="block">
            <a href="{% url 'products:product' product.pk %}">
              <img src="{{ product.image|media_folder_products }}" alt="{{ product.short_desc }}" style="width: 270px;">
              <div class="text">
                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                <h4>{{ product.name }}</h4>
                <p>{{ product.price }} </p>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <div class="clr"></div>

{% endblock %}