adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoriesListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.MyLogoutView.as_view(), name='logout'),
    path('register/', authapp.UserRegisterView.as_view(), name='register'),
    path('edit/', authapp.UserUpdateView.as_view(), name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify')
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.BasketView.as_view(), name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.BasketDeleteView.as_view(), name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

mainapp/urls.py
from django.urls import path
from .views import ProductsView, ProductView

app_name = 'mainapp'

urlpatterns = [
    path('', ProductsView.as_view(), name='products'),
    path('category/<int:pk>/', ProductsView.as_view(), name='category'),
    # path('category/<int:pk>/page/<int:page>', ProductsView.as_view(), name='page'),
    path('product/<int:pk>/', ProductView.as_view(), name='product'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import main, contact


app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contact/', contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

shop/views.py
from django.shortcuts import render


def main(request):
    context = {
        'title': 'Главная'
    }
    return render(request, 'index.html', context=context)


def contact(request):
    context = {
        'title': 'Контакты'
    }
    return render(request, 'contact.html', context=context)

shop/templates/inc/inc_footer.html
<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>

shop/templates/inc/inc_menu.html
{% load static %}
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <li>
        <a href="{% url 'index' %}" class="
            {% if request.resolver_match.url_name == 'index' %}
                active
            {% endif %}"
        >домой</a>
    </li>
    <li>
        <a href="{% url 'products:products' %}" class="
            {% if request.resolver_match.namespace == 'products' %}
                active
            {% endif %}"
        >продукты</a>
    </li>
    <li>
        <a href="{% url 'contact' %}" class="
            {% if request.resolver_match.url_name == 'contact' %}
                active
            {% endif %}"
        >контакты</a>
    </li>
    {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" href="" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                           профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'order:list' %}">
                           заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    {% endif %}
    {% if user.is_superuser %}
        <li>
            <a href="{% url 'admin_staff:users' %}">
                админка
            </a>
        </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
          <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
          <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>
    <li>
        <a href="#" class="search"></a>
    </li>
    <li>
        <a href="{% url 'basket:view' %}" class="basket">
            <span>
                {% if basket %}
                    {{ basket.0.total_cost|floatformat:0 }} руб
                    ({{ basket.0.total_quantity }} шт)
                {% endif %}
            </span>
        </a>
    </li>
</ul>